FROM node:18 AS build

WORKDIR /app

COPY journal-system-frontend/package.json journal-system-frontend/package-lock.json ./
RUN npm install

COPY journal-system-frontend/ ./
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
